// <auto-generated />
namespace _2BHLM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixingandUpdatinUserInfoTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingandUpdatinUserInfoTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107241606350_FixingandUpdatinUserInfoTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
